db:
  host: "localhost"
  port: "3306"
  username: "root"
  password: "nvuleticDevoteam1999"
  schema: "shoes_store"
  
email: 
  host: "smtp.gmail.com"
  port: "587"
  username: "nemanja.vuletic.999@gmail.com"
  password: "sotbjtfevedytngv"